/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "ArSiConfig.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Packet, Packet, 4)


PB_BIND(Packet_Config, Packet_Config, 2)


PB_BIND(Packet_Config_TX, Packet_Config_TX, 2)


PB_BIND(Packet_Config_TX_ControllerInput, Packet_Config_TX_ControllerInput, AUTO)


PB_BIND(Packet_Config_Model, Packet_Config_Model, 2)


PB_BIND(Packet_Config_Model_MixerUnit, Packet_Config_Model_MixerUnit, AUTO)


PB_BIND(Packet_Config_Model_Limits, Packet_Config_Model_Limits, AUTO)












