/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ControllerInput, ControllerInput, AUTO)


PB_BIND(TX, TX, 2)







